# https://rust-lang.github.io/rustfmt/?version=v1.5.1&search=#group_imports is
# only available in "nightly"

error_on_line_overflow = true
group_imports = "StdExternalCrate"
max_width = 120
style_edition = "2021"
